# Generated by Django 4.0.3 on 2022-04-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_historicalproduct_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmeasureunit',
            name='deleted_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='deleted_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion'),
        ),
    ]
