# Generated by Django 4.0.3 on 2022-03-30 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Elimincacion')),
                ('tipo_documento', models.CharField(choices=[('1', 'DNI'), ('6', 'RUC')], default='RUC', max_length=20, verbose_name='tipo de documento')),
                ('num_documento', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Razón Social')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Direccion')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cod_proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('type_person', models.CharField(choices=[(None, 'SIN ESPECIFICAR'), ('j', 'JURIDICA'), ('n', 'NATURAL')], default='s', max_length=11, null=True, verbose_name='Tipo de persona')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Elimincacion')),
                ('tipo_documento', models.CharField(choices=[('1', '01-FACTURA'), ('3', '03-BOLETA')], max_length=20, verbose_name='tipo de documento')),
                ('num_documento', models.CharField(help_text='factura/boleta', max_length=11, verbose_name='numero de documento')),
                ('fecha_documento', models.DateField(verbose_name='fecha de emsion del comprobante')),
                ('fecha_vencimiento', models.DateField(verbose_name='fecha de vencimiento del comprobante')),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dolares')], default='PEN', max_length=20, verbose_name='moneda')),
                ('observacion', models.TextField(blank=True, default=None, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.supplier')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('incluye_igv', models.BooleanField(default=True)),
                ('total_item', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=7)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase')),
                ('producto', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSupplier',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Elimincacion')),
                ('tipo_documento', models.CharField(choices=[('1', 'DNI'), ('6', 'RUC')], default='RUC', max_length=20, verbose_name='tipo de documento')),
                ('num_documento', models.CharField(db_index=True, max_length=11)),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Razón Social')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Direccion')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cod_proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('type_person', models.CharField(choices=[(None, 'SIN ESPECIFICAR'), ('j', 'JURIDICA'), ('n', 'NATURAL')], default='s', max_length=11, null=True, verbose_name='Tipo de persona')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Proveedor',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPurchase',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Elimincacion')),
                ('tipo_documento', models.CharField(choices=[('1', '01-FACTURA'), ('3', '03-BOLETA')], max_length=20, verbose_name='tipo de documento')),
                ('num_documento', models.CharField(help_text='factura/boleta', max_length=11, verbose_name='numero de documento')),
                ('fecha_documento', models.DateField(verbose_name='fecha de emsion del comprobante')),
                ('fecha_vencimiento', models.DateField(verbose_name='fecha de vencimiento del comprobante')),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dolares')], default='PEN', max_length=20, verbose_name='moneda')),
                ('observacion', models.TextField(blank=True, default=None, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchases.supplier')),
            ],
            options={
                'verbose_name': 'historical Compra',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
