# Generated by Django 4.0.3 on 2022-03-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_historicalsupplier_cod_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsupplier',
            name='tipo_documento',
            field=models.CharField(choices=[('6', 'RUC'), ('1', 'DNI')], default='RUC', max_length=20, verbose_name='tipo de documento'),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='type_person',
            field=models.CharField(choices=[(None, 'SIN ESPECIFICAR'), ('j', 'JURIDICA'), ('n', 'NATURAL')], default=None, max_length=20, null=True, verbose_name='Tipo de persona'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tipo_documento',
            field=models.CharField(choices=[('6', 'RUC'), ('1', 'DNI')], default='RUC', max_length=20, verbose_name='tipo de documento'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type_person',
            field=models.CharField(choices=[(None, 'SIN ESPECIFICAR'), ('j', 'JURIDICA'), ('n', 'NATURAL')], default=None, max_length=20, null=True, verbose_name='Tipo de persona'),
        ),
    ]
