# Generated by Django 4.0.3 on 2022-04-06 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_historicalsupplier_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchase',
            name='correlativo',
            field=models.CharField(default=12, max_length=8, verbose_name='correlativo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='serie',
            field=models.CharField(default='F002', max_length=4, verbose_name='serie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='correlativo',
            field=models.CharField(default='000001', max_length=8, verbose_name='correlativo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='serie',
            field=models.CharField(default='F002', max_length=4, verbose_name='serie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalpurchase',
            name='deleted_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalpurchase',
            name='fecha_documento',
            field=models.DateField(verbose_name='fecha de emision del comprobante'),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='deleted_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='type_person',
            field=models.CharField(choices=[(None, 'SIN ESPECIFICAR'), ('j', 'JURIDICA'), ('n', 'NATURAL')], default='SIN ESPECIFICAR', max_length=20, verbose_name='Tipo de persona'),
        ),
        migrations.AlterField(
            model_name='item',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchase'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='fecha_documento',
            field=models.DateField(verbose_name='fecha de emision del comprobante'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type_person',
            field=models.CharField(choices=[(None, 'SIN ESPECIFICAR'), ('j', 'JURIDICA'), ('n', 'NATURAL')], default='SIN ESPECIFICAR', max_length=20, verbose_name='Tipo de persona'),
        ),
    ]
