# Generated by Django 4.0.3 on 2022-04-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
