# Generated by Django 4.0.3 on 2022-04-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_item_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchase',
            name='total',
            field=models.CharField(default='0.00', max_length=10, verbose_name='total'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total',
            field=models.CharField(default='0.00', max_length=10, verbose_name='total'),
        ),
    ]
