# Generated by Django 4.0.3 on 2022-04-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_historicalpurchase_total_purchase_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='igv',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_item',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
    ]
