# Generated by Django 4.0.4 on 2022-06-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_alter_item_igv_alter_item_total_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchase',
            name='num_documento',
            field=models.CharField(help_text='factura/boleta', max_length=13, verbose_name='numero de documento'),
        ),
        migrations.AlterField(
            model_name='item',
            name='incluye_igv',
            field=models.BooleanField(choices=[(True, 'Incluye'), (False, 'No incluye')], default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_item',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='num_documento',
            field=models.CharField(help_text='factura/boleta', max_length=13, verbose_name='numero de documento'),
        ),
    ]
