# Generated by Django 4.0.4 on 2022-06-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_alter_historicalpurchase_num_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsupplier',
            name='type_person',
            field=models.CharField(choices=[(None, 'SIN ESPECIFICAR'), ('j', 'JURIDICA'), ('n', 'NATURAL')], default='SIN ESPECIFICAR', max_length=20, null=True, verbose_name='Tipo de persona'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type_person',
            field=models.CharField(choices=[(None, 'SIN ESPECIFICAR'), ('j', 'JURIDICA'), ('n', 'NATURAL')], default='SIN ESPECIFICAR', max_length=20, null=True, verbose_name='Tipo de persona'),
        ),
    ]
