# Generated by Django 4.0.4 on 2022-06-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_alter_historicalsupplier_type_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsupplier',
            name='type_person',
            field=models.CharField(choices=[(None, 'SIN ESPECIFICAR'), ('j', 'JURIDICA'), ('n', 'NATURAL')], default='SIN ESPECIFICAR', max_length=4, null=True, verbose_name='Tipo de persona'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type_person',
            field=models.CharField(choices=[(None, 'SIN ESPECIFICAR'), ('j', 'JURIDICA'), ('n', 'NATURAL')], default='SIN ESPECIFICAR', max_length=4, null=True, verbose_name='Tipo de persona'),
        ),
    ]
