# Generated by Django 4.0.4 on 2022-06-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_alter_historicalsupplier_type_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsupplier',
            old_name='name',
            new_name='legal_name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='name',
            new_name='legal_name',
        ),
    ]
