# Generated by Django 4.0.4 on 2022-07-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_rename_name_historicalsupplier_legal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='igv',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_item',
            field=models.IntegerField(null=True),
        ),
    ]
