# Generated by Django 4.0.4 on 2022-07-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_alter_item_igv_alter_item_total_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchase',
            name='total',
            field=models.IntegerField(default='0.00', max_length=10, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='item',
            name='igv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.IntegerField(default='0.00', max_length=10, verbose_name='total'),
        ),
    ]
