# Generated by Django 4.0.4 on 2022-07-29 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0014_alter_historicalpurchase_total_alter_item_igv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='incluye_igv',
        ),
    ]
