# Generated by Django 4.0.4 on 2022-07-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0015_remove_item_incluye_igv'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchase',
            name='igv',
            field=models.IntegerField(default=0, max_length=10, verbose_name='total'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='igv',
            field=models.IntegerField(default=0, max_length=10, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='historicalpurchase',
            name='total',
            field=models.IntegerField(default=0, max_length=10, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.IntegerField(default=0, max_length=10, verbose_name='total'),
        ),
    ]
