# Generated by Django 4.0.4 on 2022-08-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0018_alter_historicalpurchase_igv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='state',
        ),
    ]
