# Generated by Django 4.1 on 2022-09-19 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0019_remove_item_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpurchase",
            name="abonado",
            field=models.IntegerField(default=0, verbose_name="total"),
        ),
        migrations.AddField(
            model_name="historicalpurchase",
            name="pagada",
            field=models.BooleanField(default=True, verbose_name="pago completado"),
        ),
        migrations.AddField(
            model_name="purchase",
            name="abonado",
            field=models.IntegerField(default=0, verbose_name="total"),
        ),
        migrations.AddField(
            model_name="purchase",
            name="pagada",
            field=models.BooleanField(default=True, verbose_name="pago completado"),
        ),
        migrations.AlterField(
            model_name="historicalpurchase",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("1", "01-FACTURA"),
                    ("3", "03-BOLETA"),
                    ("2", "RECIBO POR HONORARIOS"),
                    ("13", "CONSTANCIA DE DEPOSITO"),
                    ("14", "RECIBOS POR SERVICIO"),
                ],
                max_length=20,
                verbose_name="tipo de documento",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="proveedor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="purchases.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("1", "01-FACTURA"),
                    ("3", "03-BOLETA"),
                    ("2", "RECIBO POR HONORARIOS"),
                    ("13", "CONSTANCIA DE DEPOSITO"),
                    ("14", "RECIBOS POR SERVICIO"),
                ],
                max_length=20,
                verbose_name="tipo de documento",
            ),
        ),
    ]
