# Generated by Django 4.1 on 2022-09-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchases",
            "0020_historicalpurchase_abonado_historicalpurchase_pagada_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpurchase",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("0", "INTERNO"),
                    ("1", "01-FACTURA"),
                    ("3", "03-BOLETA"),
                    ("2", "RECIBO POR HONORARIOS"),
                    ("13", "CONSTANCIA DE DEPOSITO"),
                    ("14", "RECIBOS POR SERVICIO"),
                ],
                max_length=20,
                verbose_name="tipo de documento",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("0", "INTERNO"),
                    ("1", "01-FACTURA"),
                    ("3", "03-BOLETA"),
                    ("2", "RECIBO POR HONORARIOS"),
                    ("13", "CONSTANCIA DE DEPOSITO"),
                    ("14", "RECIBOS POR SERVICIO"),
                ],
                max_length=20,
                verbose_name="tipo de documento",
            ),
        ),
    ]
